export { default as IntroSection } from './IntroSection/IntroSection.component';
export { default as IntroTypingSection } from './IntroTypingSection/IntroTypingSection.component';
export { default as IntroTyping } from './IntroTyping/IntroTyping.component';
export { default as IntroTypingMobile } from './IntroTypingMobile/IntroTypingMobile.component';
export { default as PlatformIntroduceSection } from './PlatformIntroduceSection/PlatformIntroduceSection.component';
export { default as JoinRecruitCard } from './JoinRecruitCard/JoinRecruitCard.component';
export { default as ActivitySection } from './ActivitySection/ActivitySection.component';
export { default as ActivityItem } from './ActivityItem/ActivityItem.component';
export { default as CurrentInformationSection } from './CurrentInformationSection/CurrentInformationSection.component';
